name: Deploy Sentinel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          rm -rf /home/dian/projects/sentinel/sentinel-go
          git clone https://git.winandahartadi.cloud/fallenguava/sentinel-go.git /home/dian/projects/sentinel/sentinel-go

      - name: Build
        run: |
          cd /home/dian/projects/sentinel/sentinel-go
          go build -o bin/sentinel ./cmd/sentinel/

      - name: Restart service
        run: sudo systemctl restart sentinel-go
